FROM python:3.8
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY backend/ .
# Download nltk dependenceies
RUN [ "python", "-c", "import nltk; nltk.download('stopwords')" ]
EXPOSE 8073
CMD ["gunicorn", "-b", ":8073", "wsgi:app"]