CNN:
  sitemap_url: https://www.cnn.com/sitemaps/cnn/news.xml
  xml_parser: >-
    lambda xml: [{
      'title': e.find('{http://www.google.com/schemas/sitemap-news/0.9}news')[2].text,
      'url': e[0].text
      } for e in xml.findall('{http://www.sitemaps.org/schemas/sitemap/0.9}url')]
  article_parser: >-
    lambda soup: ",".join([e.get_text() for e in soup.find_all("div", {"class":"zn-body__paragraph"})])
FOX:
  sitemap_url: https://www.foxnews.com/sitemap.xml?type=news
  xml_parser: >-
    lambda xml: [{
      'title': e.find('{http://www.google.com/schemas/sitemap-news/0.9}news')[2].text,
      'url': e[0].text
      } for e in xml.findall('{http://www.sitemaps.org/schemas/sitemap/0.9}url')]
  article_parser: >-